UN-OCHA/iasc8

.github/workflows/docker-build-develop.yml, docker/Dockerfile, docker/services.yml, docker/settings.php
Add our basic settings.php that uses env varibales to create a database connection and that loads any additonal config from snippets in a mounted volume.
Add a GitHub Action that builds the develop image on merge.
=> [OPS-5482] Allow self-contained builds for k8s.

config/views.view.search_content.yml, html/themes/custom/iasc_common_design/templates/node/node--oa-wiki-page--teaser.html.twig, html/themes/custom/iasc_common_design/templates/node/node--oa-wiki-page--title.html.twig
1. Search Views no results message
2. document content type override for teaser and title view mode, node title links to file URL if show page instead of file checkbox is unchecked
=> IASC-561 common design

config/core.entity_view_display.media.image.teaser.yml, config/core.entity_view_display.paragraph.teaser_item.default.yml, config/core.entity_view_mode.media.thumbnail.yml, html/themes/custom/common_design/common_design.theme, html/themes/custom/iasc_common_design/iasc_common_design.theme
1.  thumbnail media display mode for teaser item image style
2. rename thumbnail media view mode to reflect image style 'featured thumbnail'
3. Sort out Views exposed form preprocess - remove from common_design, add conditional for form ID in sub theme
=> IASC-561 teaser item image style

html/modules/custom/iasc_content/iasc_content.module
- Internal links, title defaults to entity title
- External links, title defaults to url
=> Add custom links to section menu

config/block.block.authoredon.yml, config/block.block.contenttype.yml, config/core.entity_view_display.media.file.link.yml, config/facets.facet.search_authored_on.yml, config/facets.facet.search_content_type.yml, config/views.view.search_content.yml, html/themes/custom/iasc_common_design/iasc_common_design.theme, html/themes/custom/iasc_common_design/templates/page--404.html.twig, html/themes/custom/iasc_common_design/templates/page--search.html.twig
1. 404 page override (give back to common_design)
2. Facets for search, placed in sidebar (but not showing)
3. Search page title in Views header
=> IASC-561 search page with facets

config/core.entity_form_display.node.panopoly_page.default.yml, config/core.entity_view_display.node.panopoly_page.default.yml, config/core.entity_view_display.node.panopoly_page.featured.yml, config/field.field.node.panopoly_page.field_content.yml, config/field.field.node.panopoly_page.field_sidebar.yml
1. content page content type paragraph button style, include more para types, hide legacy fields from form and display
=> IASC-561 more config

config/block.block.audience.yml, config/block.block.audiencelabel.yml, config/block.block.resourceaudiencelabel.yml, config/block.block.resourcedocumentsaudiencelabel.yml, config/block.block.resourcedocumentsauthoredon.yml, config/block.block.resourcedocumentsdocumenttypelabel.yml, config/block.block.resourceproductsauthoredon.yml, config/block.block.resourceproductsdocumenttypelabel.yml, config/block.block.resourcesauthoredon.yml, config/block.block.resourcescontenttype.yml, config/block.block.resourcesdocumenttypelabel.yml, config/block.block.resourcesproductcategorylabel.yml, config/facets.facet.search_audience.yml, config/facets.facet.search_audience_label.yml, config/facets.facet.search_content_type.yml, html/themes/custom/iasc_common_design/templates/views/views-view--search-content.html.twig
1. add audience facet to search, place block and fix one block title
2. Message on search page for anon users prompting login for more results
=> IASC-561 add audience facet to search, place block and fix one block title

config/search_api.index.default_solr_index.yml, config/views.view.resources.yml
1. publish date added to solr
2. ordered by published date
=> IASC-561 newsletter view 

config/system.site.yml
Newly created landing page node for homepage
=> IASC-561 connect front page to node/40181

config/views.view.resources.yml, config/views.view.search_content.yml
not search result view mode for most content types
=> IASC-593 config resources view and search view to use teasers

config/filter.format.iasc_wysiwyg.yml, html/themes/custom/iasc_common_design/templates/node/node--oa-event--full.html.twig
To make `<p>` tags work for pages with IASC WYSIWYG
=> IASC-561 add p tag to allowed html for IASC wysiwyg

config/facets.facet.resource_documents_authored_on.yml, config/facets.facet.resource_products_authored_on.yml, config/facets.facet.resources_authored_on.yml, config/facets.facet.search_authored_on.yml
Sort by raw value for all Authored on facets
=> IASC-561 order Resource facet for Authored on to match Documents

config/views.view.documents.yml
blocks x 2 sort order set to published date, not changed date
=> IASC-561 recent document block order

config/views.view.iasc_contacts.yml, html/themes/custom/iasc_common_design/templates/cd/cd-footer/cd-soft-footer.html.twig
1. co-chairs block plural
2. IASC newsletter copy
=> IASC-601 IASC-602

config/views.view.resources.yml
=> IASC-561 expand IASC products View to include statements

config/views.view.iasc_group_content.yml
=> IASC-609 change sort order to have published date before authored on date

config/core.entity_view_display.node.announcement.teaser.yml, config/views.view.iasc_group_content.yml, html/themes/custom/iasc_common_design/templates/node/node--teaser.html.twig
1. use twig filter to strip tags from teaser body field
2. display thumbnail image on announcement teasers
3. set group content to use teaser not search result view mode
=> IASC-608 teaser formatting

config/core.date_format.published_date.yml
=> IASC-617 change published date to UN format

composer.json, composer.lock, html/themes/custom/iasc_common_design/templates/cd/cd-footer/cd-footer.html.twig
update the common_design to a new release version 2.4.0
=> CD-177 adjust footer block in anticipation of common_design changes

config/core.entity_view_display.node.announcement.featured.yml, config/core.entity_view_display.node.oa_event.featured.yml, config/core.entity_view_display.node.oa_wiki_page.featured.yml
Config to remove date display from Feature items for Announcements, Documents, Events
=> IASC-637 hide date on Feature view mode

config/core.menu.static_menu_link_overrides.yml
Disable "My account"
New menu item for %username% should be created (content)
=> IASC usermenu configuration

config/core.entity_view_display.node.contact.bio_full.yml, config/core.entity_view_display.node.contact.bio_full_.yml, config/core.entity_view_display.node.contact.bio_long.yml, config/core.entity_view_display.node.contact.default.yml, config/core.entity_view_display.node.contact.teaser.yml, config/views.view.iasc_contacts.yml, html/themes/custom/iasc_common_design/templates/node/node--contact--bio-long.html.twig
1. Remove phone number field from display and template
2. Set Chair block to use bio long display, to be consistent with Co-chair
=> IASC-616 contact bio long

composer.json, composer.lock, composer.patches.json
remove patch for symfony version https://www.drupal.org/node/2876675
=> update base theme, remove patch for base theme fix

composer.json, composer.lock
1. `composer require/drupal stage_file_proxy`
2. To do: Needs config to enable
=> OPS-6763 Stage file proxy module 

composer.json, composer.lock, html/modules/custom/iasc_content/templates/block--iasc-header-search-block.html.twig, html/themes/custom/iasc_common_design/templates/cd/cd-footer/cd-soft-footer.html.twig, html/themes/custom/iasc_common_design/templates/page--404.html.twig, html/themes/custom/iasc_common_design/templates/page--group--documents.html.twig, html/themes/custom/iasc_common_design/templates/page--group.html.twig, html/themes/custom/iasc_common_design/templates/page.html.twig
bump base theme version and make some changes to sub theme to reflect recent updates to base theme
=> Update base theme

html/themes/custom/iasc_common_design/templates/page--group--documents.html.twig, html/themes/custom/iasc_common_design/templates/page--group.html.twig
add group layout classes after accidentally removing during base theme update adjustments
=> Fix layout after updating base theme

config/views.view.search_content.yml
remove result count in Views header area
=> IASC-661 facet summary

config/block.block.exposed_form_iasc_services.yml
Remove landing page from Visibility rules for Search block
=> AAP-35 landing page

composer.json, composer.lock, config/core.extension.yml, config/image.style.hero.yml, html/modules/custom/iasc_hero/templates/hero.html.twig
1. Install and enable Twig tweak module
2. Use hero image style in hero template
3. Adjust hero image width in image style
=> AAP-35 hero image style

config/block.block.breadcrumbs.yml, config/block.block.feature_request.yml, config/block.block.feedback.yml, config/block.block.mainpagecontent.yml, config/block.block.messages.yml, config/block.block.tabs.yml
add 2 x custom blocks to content region, with IDs from Prod
=> Custom block config for AAP block on Prod

html/themes/custom/iasc_common_design/package-lock.json, html/themes/custom/iasc_common_design/package.json
=> Dependency updates for sub theme

html/themes/custom/iasc_common_design/templates/paragraphs/paragraph--services-landing-block.html.twig
=> AAP-39 remove stray library, no longer exists

config/facets_summary.facets_summary.services_summary.yml
- Disable those fields not used
- Reorder relevant fields to reflect block order
=> AAP-39 reorder fields in summary so they reflect block order

html/themes/custom/iasc_common_design/package-lock.json, html/themes/custom/iasc_common_design/package.json
=> Dependency updates for subtheme

html/modules/custom/select_a11y/src/Plugin/facets/widget/DropdownWidget.php
@see https://github.com/UN-OCHA/iasc8/pull/418
=> Fixed module name

html/themes/custom/iasc_common_design/gulpfile.js, html/themes/custom/iasc_common_design/package-lock.json, html/themes/custom/iasc_common_design/package.json
1. axios version update and `npm audit fix`
2. replace gulp-sass with dart-sass
=> CD-213 dependency updates

composer.json, composer.lock, html/themes/custom/iasc_common_design/templates/cd/cd-footer/cd-footer.html.twig, html/themes/custom/iasc_common_design/templates/cd/cd-header/cd-global-header.html.twig
As per AR-208 this should fix the Username variable caching issue, with a base theme update.
Also included are some improvements to the OCHA Services menu. To accommodate the moving of the OCHA Services partial to the footer, I've made the same changes in the sub theme.
=> CD-246 update base theme

config/core.entity_view_display.node.panopoly_landing_page.full.yml
So settings for page title works
=> IASC-683 Add full view mode to landing page content type

package-lock.json, package.json
=> OPS-7442 xmldom as dev dependency

composer.lock, config/iasc_common_design.settings.yml
=> IASC-683 fix page title issue

html/themes/custom/iasc_common_design/package-lock.json, html/themes/custom/iasc_common_design/package.json
Attempt to update trim - as per https://github.com/UN-OCHA/common_design/pull/220/files
=> update package.json for dependabot alert

composer.lock, composer.patches.json, html/robots.txt
I also added a link to the search_api patch to make it easier to find, for reference.
=> IASC-703 / IASC-704 Add patch to fix Views read more link disappearing

html/themes/custom/iasc_common_design/package-lock.json, html/themes/custom/iasc_common_design/package.json, package-lock.json, package.json
for pwmetrics/lighthouse and base theme
=> Dependency updates

composer.json, composer.lock, html/.gitignore, html/modules/.gitignore, html/profiles/.gitignore, html/sites/.gitignore, html/themes/.gitignore
https://humanitarian.atlassian.net/browse/OPS-7544
Security update to ctools module
(And include some .gitignore files that weren't checked in.)
=> [OPS-7544] update ctools module

html/themes/custom/iasc_common_design/package-lock.json, html/themes/custom/iasc_common_design/package.json
- manually update xmldom from github package
=> CD-298 dependency updates

composer.lock
https://humanitarian.atlassian.net/browse/OPS-7794
Fixes https://www.drupal.org/sa-contrib-2021-034
Release notes: https://www.drupal.org/project/search_api_attachments/releases/8.x-1.0-beta18
=> [OPS-7794] update search_api_attachments

package-lock.json, package.json
In root package.json, re-arrange for alphabetical, regen lock file
=> CD-289 xmldom and json-schema as dev dependencies

.github/workflows/docker-build-image.yml
=> [OPS-7896] Flip the IASC site to ECR.

composer.lock, symfony.lock
Run `composer update` generates new lock file and `symfony.lock`
=> Dependency updates for symfony/serializer based on Dependabot alert

composer.json, composer.lock
https://humanitarian.atlassian.net/browse/IASC-724
Security update to webform module
=> [IASC-724] update webform module

composer.json, composer.lock, config/core.extension.yml, config/honeypot.settings.yml, config/tour.tour.honeypot.yml, config/webform.webform.service_contact.yml, symfony.lock
Following on from https://github.com/UN-OCHA/iasc8/pull/550, webform recommends including some libraries and the honeypot module. This low-priority PR adds those.
It can be deployed at a later date.
=> [IASC-724] add libraries for webform and honeypot module, as recommended

config/seckit.settings.yml
https://humanitarian.atlassian.net/browse/OPS-7743
More details on the ticket, this adds some missed sources and tidies up a bit.
=> [OPS-7743] update seckit configuration

composer.lock, symfony.lock
https://humanitarian.atlassian.net/browse/OPS-7998
Module updates for geofield, geofield_map, paragraphs_edit and search_api_solr.
=> [OPS-7998] update contrib modules

composer.json, composer.lock, html/sites/default/default.services.yml, html/sites/default/default.settings.php
Ideally we can get this one sorted and rolled into https://github.com/UN-OCHA/iasc8/pull/561 so I can fix the broken files tomorrow.
=> [OPS-8029] Drupal 9.3.3 security plus a composer tweak.

composer.lock, composer.patches.json, symfony.lock
https://humanitarian.atlassian.net/browse/IASC-728
See https://www.drupal.org/project/webform/issues/3264249
=> [IASC-728] add patch for temporary webform library issue

.travis.yml, composer.json, composer.lock, html/modules/custom/iasc_content/src/EventSubscriber/ParagraphSummaryAlter.php, html/modules/custom/select_a11y/src/Element/SelectA11y.php, symfony.lock
Similar to https://github.com/UN-OCHA/slt8-site/pull/61 but trying a simplified change in .travis.yml.
=> [OPS-7997] update coder module and revert travis config

composer.lock
[OPS-8203]
update search_api module to 1.23.0
[OPS-8203]: https://humanitarian.atlassian.net/browse/OPS-8203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OPS-8203] update search_api module to 1.23.0

config/user_expire.settings.yml
[OPS-8147]
[OPS-8147]: https://humanitarian.atlassian.net/browse/OPS-8147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OPS-7459] user expire notification message

config/views.view.files_used_in_nodes.yml
=> feat: Private files used on nodes

composer.json, composer.lock, composer.patches.json, config/core.extension.yml, config/seckit.settings.yml, symfony.lock
=> chore: improvements for seckit

Makefile, composer.json, composer.lock, composer.patches.json, config/core.extension.yml, config/seckit.settings.yml, config/views.view.files_used_in_nodes.yml, symfony.lock
=> Seckit update and add export

config/views.view.list_of_users.yml
=> feat: Export users

composer.patches.json, config/views.view.group_content_export.yml, config/views.view.iasc_event_file_export.yml
=> fix: Patch core so we can access files attached to content via Views.

html/modules/custom/iasc_content/src/Controller/GroupMeetings.php
=> feat: Paging by months

config/core.entity_form_display.paragraph.meetings_past.default.yml, config/core.entity_form_display.paragraph.meetings_upcoming.default.yml, config/core.entity_view_display.paragraph.meetings_past.default.yml, config/core.entity_view_display.paragraph.meetings_upcoming.default.yml, config/field.field.group.iasc_space.field_content.yml, config/field.field.group.iasc_space.field_sidebar.yml, config/field.field.paragraph.meetings_past.field_link_to_all_meetings.yml, config/field.field.paragraph.meetings_past.field_max_number_of_events.yml, config/field.field.paragraph.meetings_upcoming.field_link_to_all_meetings.yml, config/field.field.paragraph.meetings_upcoming.field_max_number_of_events.yml, config/field.storage.paragraph.field_link_to_all_meetings.yml, config/field.storage.paragraph.field_max_number_of_events.yml, config/paragraphs.paragraphs_type.meetings_past.yml, config/paragraphs.paragraphs_type.meetings_upcoming.yml, config/user.settings.yml, html/modules/custom/iasc_content/iasc_content.module, html/modules/custom/iasc_content/src/Controller/GroupMeetings.php, html/modules/custom/iasc_content/templates/iasc-content-pager.html.twig, html/themes/custom/iasc_common_design/templates/iasc-content-pager.html.twig
=> feat: Disable account creation

config/field.field.group.iasc_space.field_content.yml, config/paragraphs.paragraphs_type.meetings_past.yml, config/paragraphs.paragraphs_type.meetings_upcoming.yml
=> chore: Rename paragraph names

composer.lock, symfony.lock
Refs: OPS-7520
As with https://github.com/UN-OCHA/odsg8-site/pull/114 - this updates the packages that were causing problems in https://github.com/UN-OCHA/iasc8/runs/6913444925?check_suite_focus=true - so the update script should be able to run.
=> fix: update packages that were blocking composer install

html/modules/custom/iasc_content/src/Controller/GroupMeetings.php
=> bug: until

html/themes/custom/iasc_common_design/templates/node/node--oa-event--full.html.twig, html/themes/custom/iasc_common_design/templates/views/views-view--search-content.html.twig
=> IASC-737 Remove login prompts

composer.json, composer.lock, html/themes/custom/iasc_common_design/components/cd-filter/cd-filter.css
=> IASC-736 Udate base theme to recent version v7.2.0

html/modules/custom/iasc_content/iasc_content.module
=> bug: Allow infinite repeats

html/themes/custom/iasc_common_design/components/iasc-custom/node--event.css, html/themes/custom/iasc_common_design/components/iasc-custom/node.css, html/themes/custom/iasc_common_design/iasc_common_design.libraries.yml, html/themes/custom/iasc_common_design/iasc_common_design.theme, html/themes/custom/iasc_common_design/js/local_time.js, html/themes/custom/iasc_common_design/templates/field/field--field-oa-date.html.twig, html/themes/custom/iasc_common_design/templates/node/node--oa-event--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--oa-event--teaser.html.twig
=> bug: local time

html/themes/custom/iasc_common_design/components/iasc-custom/node--event.css, html/themes/custom/iasc_common_design/js/local_time.js, html/themes/custom/iasc_common_design/templates/node/node--oa-event--teaser.html.twig
=> bug: display time on teaser

html/modules/custom/iasc_content/iasc_content.module, html/modules/custom/iasc_content/src/Controller/GroupMeetings.php, html/themes/custom/iasc_common_design/iasc_common_design.theme, html/themes/custom/iasc_common_design/js/local_time.js, html/themes/custom/iasc_common_design/templates/node/node--oa-event--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--oa-event--teaser.html.twig
- fix timezone with occurrences
- add extra info for all day events in other timezone
- add support for events spanning multiple days
- use Date objects where possible
Refs: #IASC-753
=> feat: various fixes

html/themes/custom/iasc_common_design/iasc_common_design.theme, html/themes/custom/iasc_common_design/js/local_time.js, html/themes/custom/iasc_common_design/templates/field/field--field-oa-date.html.twig, html/themes/custom/iasc_common_design/templates/node/node--oa-event--teaser.html.twig
=> feat: multi day event

html/themes/custom/iasc_common_design/js/local_time.js
=> feat: use js utc methods

html/modules/custom/iasc_content/iasc_content.install, html/modules/custom/iasc_content/iasc_content.module
=> feat: Replace all event blocks with new ones

html/themes/custom/iasc_common_design/components/iasc-custom/node--event.css
=> IASC-753 Adjust vertical rhythm for teaser event fields

PATCHES/csp-log-format.patch, composer.patches.json
=> fix: include patch for clearer logging

html/themes/custom/iasc_common_design/templates/html--front.html.twig
in html template override for frontpage
Refs: IASC-749
=> IASC-749 Google search script

config/pathauto.pattern.content_contacts.yml, config/pathauto.pattern.node_oa_group.yml, config/pathauto.pattern.node_oa_space.yml, config/pathauto.pattern.node_panopoly_landing_page.yml, config/pathauto.pattern.service_nodes.yml
=> fix: update pathauto config

composer.json, composer.lock
=> fix: Switch to our packagist-hosted file_checker module, which does D9.

html/themes/custom/iasc_common_design/components/iasc-cd-header-footer/cd-soft-footer.css, html/themes/custom/iasc_common_design/templates/cd/cd-footer/cd-soft-footer.html.twig
- set colour for visual hidden heading
- remove label for input type submit
- add attributes to hidden input
Refs: IASC-756
=> IASC-757 Mailchimp accessibility fixes

html/themes/custom/iasc_common_design/components/iasc-custom/paragraph.css
=> IASC-757 additional rules to move heading border to next element when there is no heading

html/modules/custom/iasc_content/src/Plugin/Block/IascContentSectionMenu.php
=> fix: bail when we have no group

config/social_auth_hid.settings.yml
=> feat: Allow user create so admin can add editors

config/social_auth_hid.settings.yml
This reverts commit 7969f70d57fb0185b277671c3eec8186621581c4.
=> Revert "feat: Allow user create so admin can add editors"

config/search_api.index.default_solr_index.yml, config/search_api.index.services.yml
Refs: OPS-8623
Tried something similar for CERF but couldn't get it to deploy. Trying the same again here. Related to: https://www.drupal.org/project/search_api_solr/issues/3314711
=> fix: update search_api_solr config

config/search_api.index.default_solr_index.yml, config/search_api.index.services.yml
Refs: OPS-8623
A variation on: https://github.com/UN-OCHA/iasc8/pull/717 - which worked but required re-indexing everything. This makes it more general for sites that have more than one language enabled.
=> fix: handle new search_api_solr config

html/modules/custom/iasc_service/src/Controller/IascServicesSearch.php
Introduced by https://github.com/UN-OCHA/iasc8/commit/ec5827beb17927279b0205b7c512bb013c8c37b0
Refs: #IASC-763
=> bug: Service search

composer.patches.json, config/search_api_attachments.admin_config.yml
=> fix: Make search_api_attachments not use the database k/v store as cache

composer.json, composer.lock, config/core.extension.yml, config/xmlsitemap.settings.group.iasc_group.yml, config/xmlsitemap.settings.group.iasc_space.yml, config/xmlsitemap.settings.menu_link_content.menu_link_content.yml, config/xmlsitemap.settings.node.announcement.yml, config/xmlsitemap.settings.node.oa_event.yml, config/xmlsitemap.settings.node.oa_section.yml, config/xmlsitemap.settings.node.oa_wiki_page.yml, config/xmlsitemap.settings.node.panopoly_landing_page.yml, config/xmlsitemap.settings.node.panopoly_page.yml, config/xmlsitemap.settings.node.service.yml, config/xmlsitemap.settings.yml, config/xmlsitemap.xmlsitemap.g3XYqcXbSKPVBDODwnT6pq7oqhCFkPryj4vVqrl_Kfc.yml
=> feat: Add XML sitemap

html/themes/custom/iasc_common_design/components/iasc-custom/facets.css, html/themes/custom/iasc_common_design/components/iasc-custom/field.css, html/themes/custom/iasc_common_design/components/iasc-custom/node.css, html/themes/custom/iasc_common_design/components/iasc-custom/paragraph.css, html/themes/custom/iasc_common_design/components/iasc-custom/section-menu.css, html/themes/custom/iasc_common_design/components/iasc-custom/views.css, html/themes/custom/iasc_common_design/css/typography.css
After testing this PR https://github.com/UN-OCHA/iasc8/pull/719 all is good.
chore: remove commented out code after testing
Refs: IASC-690
=> CD-411 and IASC-690 Code tidy

config/redirect.settings.yml
=> chore: Disable redirect

config/views.view.files_used_in_nodes.yml
=> feat: Extra fields

package-lock.json, package.json
Doesn't solve issues with PWMetrics - see https://humanitarian.atlassian.net/browse/OPS-8905 - but does bring other packages up to date. This hasn't been tested.
=> update packages in main

config/views.view.files_used_in_nodes.yml
=> feat: extra fields for export

composer.json, docker/Dockerfile
=> chore: try to fix build failure

docker/Dockerfile
=> chore: try again at including config

html/modules/custom/iasc_content/iasc_content.routing.yml, html/modules/custom/iasc_content/src/Controller/GroupMeetings.php
=> bug: add cache contexts and tags

html/modules/custom/iasc_content/src/Controller/GroupMeetings.php
=> debug: add cache contexts and tags

html/modules/custom/iasc_content/iasc_content.module
=> bug: Make sure entity exists

composer.json, composer.lock, config/core.extension.yml
This is needed for group update and needs to be deployed before the actual upgrade.
=> chore: Add flexible permissions

config/views.view.group_nodes.yml, html/modules/custom/iasc_content/iasc_content.module
=> bug: getContentPlugin is obsolete

.github/workflows/run-tests.yml
=> chore: use automatic php detection

.github/workflows/run-tests.yml
=> fix: include php detection action

.github/workflows/run-tests.yml, phpunit.xml
=> chore: add code-coverage

config/group.role.iasc_group-admin.yml, config/group.role.iasc_group-anonymous.yml, config/group.role.iasc_group-global_admin_in.yml, config/group.role.iasc_group-member.yml, config/group.role.iasc_group-outsider.yml, config/group.role.iasc_space-admin.yml, config/group.role.iasc_space-anonymous.yml, config/group.role.iasc_space-global_admin_in.yml, config/group.role.iasc_space-member.yml, config/group.role.iasc_space-outsider.yml
=> bug: Admin permissions as insider

html/themes/custom/iasc_common_design/components/iasc-cd-header-footer/cd-layout.css, html/themes/custom/iasc_common_design/components/iasc-custom/field.css, html/themes/custom/iasc_common_design/components/iasc-custom/node.css, html/themes/custom/iasc_common_design/components/iasc-custom/paragraph.css, html/themes/custom/iasc_common_design/templates/group/group.html.twig, html/themes/custom/iasc_common_design/templates/layout/page--group--documents.html.twig, html/themes/custom/iasc_common_design/templates/layout/page--group--meetings.html.twig, html/themes/custom/iasc_common_design/templates/layout/page--group--news.html.twig, html/themes/custom/iasc_common_design/templates/layout/page--group.html.twig, html/themes/custom/iasc_common_design/templates/layout/page--rg2.html.twig, html/themes/custom/iasc_common_design/templates/layout/page.html.twig, html/themes/custom/iasc_common_design/templates/node/node--action-point--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--announcement--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--contact--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--oa-event--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--oa-section--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--oa-wiki-page--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--service--full.html.twig
Find-n-replace some CD classnames.
=> [OPS-9660] Fix CD layouts

html/themes/custom/iasc_common_design/templates/group/group.html.twig, html/themes/custom/iasc_common_design/templates/layout/page--rg2.html.twig, html/themes/custom/iasc_common_design/templates/node/node--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--oa-event--full.html.twig, html/themes/custom/iasc_common_design/templates/node/node--panopoly-landing-page--full.html.twig
=> fix(ui): another sidebar fix

html/themes/custom/iasc_common_design/templates/layout/page--group--documents.html.twig
=> fix(ui): column layout for facets page

composer.lock
Refs: 862
Replaces https://github.com/UN-OCHA/iasc8/pull/862
=> chore: Composer update

composer.json, composer.lock
Refs: updates
This got tangled in support of D10 - https://www.drupal.org/project/csv_serialization/issues/3396149 sorts it out by creating a 4.x branch.
=> chore: update csv_serialization module

composer.json, composer.lock
Update base theme from v8 to v9.2 which includes the replacement of twitter icon asset with x icon
Refs: CD-520
Expected result:
=> CD-520 Update base theme to v9 to avail of x icon replacing twitter

local/README.md, local/install.sh
Updating local stack with more recent additions from drupal-starterkit
=> Update readme and install script with recent from starterkit

local/.env.example, local/docker-compose.yml, local/shared/settings/services.yml, local/shared/settings/settings.local.php
=> chore: update local stack for consistency

composer.json, composer.lock, docker/Dockerfile
=> chore: Bump the project to PHP 8.3 and update the composer files to match.

.docksal/docksal.env, composer.json, composer.lock, html/themes/custom/iasc_common_design/templates/cd/cd-header/cd-global-header.html.twig
Depending on your services/settings, your local might need a cache-rebuild to jiggle OCHA Services back into the header since it required a template change. Our remote environments will not need any special action.
=> [CD-533] Upgrade IASC to CD v9.3.2

.github/workflows/docker-build-image.yml, .github/workflows/run-tests.yml
=> chore: bump github actions

config/views.view.files.yml
=> feat: add delete button for files

composer.json, composer.lock
Refs: IASC-790
Already uninstalled in IASC-790 and https://humanitarian.atlassian.net/browse/OPS-10019 this cleans up the leftovers.
=> chore: remove uninstalled chosen module

composer.json, composer.lock, tests/docker-compose.yml
Refs: OPS-10520
The version change in composer.json will have to be reverted before the next deployment.
=> chore: revert core version until changes can be better tested

composer.json, composer.lock
=> chore: revert for core-composer-scaffold and -project-message too

config/seckit.settings.yml
=> chore: fix typo that broke csp directives

PATCHES/disable-webform-help-video.patch, composer.json, composer.lock, composer.patches.json, config/monitoring.sensor_config.core_cron_last_run_age.yml, config/monitoring.sensor_config.monitoring_installed_modules.yml, config/monitoring.sensor_config.ocha_admin_paths.yml, config/monitoring.sensor_config.ocha_common_design.yml, config/monitoring.sensor_config.ocha_current_composer_version.yml, config/monitoring.sensor_config.ocha_current_drupal_version.yml, config/monitoring.sensor_config.ocha_current_php_version.yml, config/monitoring.sensor_config.ocha_current_release.yml, config/monitoring.sensor_config.ocha_deployment_identifier.yml, config/monitoring.sensor_config.ocha_env_link_fixer.yml, config/monitoring.sensor_config.ocha_gtm_barebones.yml, config/monitoring.sensor_config.ocha_ocha_monitoring.yml, config/monitoring.sensor_config.ocha_un_date.yml, config/monitoring.sensor_config.update_contrib.yml, config/monitoring.sensor_config.update_core.yml, config/views.view.group_content_export.yml, config/views.view.groups_overview.yml, config/views.view.iasc_event_file_export.yml
=> bug: Fix access to admin paths

composer.json, composer.lock
=> chore: remove quickedit module which has been uninstalled for a year

config/seckit.settings.yml
=> chore: another csp domain

config/seckit.settings.yml
=> chore: add csp domains

config/seckit.settings.yml
=> chore: more csp domains

html/themes/custom/iasc_common_design/iasc_common_design.theme
Refs: IASC-800
Explanation on the ticket.
=> fix: specify locale when missing

config/seckit.settings.yml
=> chore: fix typo

PATCHES/core_js_optimizer.patch, composer.patches.json, html/themes/custom/iasc_common_design/js/local_time.js, html/themes/custom/iasc_common_design/js/login_destination.js, html/themes/custom/iasc_common_design/js/region_num_childs.js
Refs: IASC-799
The patch from https://www.drupal.org/project/drupal/issues/3416508 seems to fix the errors.
The js clean-up was suggested by linting - it didn't fix the problem, but is probably worth keeping.
=> fix: optimize errors

config_dev/stage_file_proxy.settings.yml, config_dev/views.view.watchdog.yml
=> chore: update sfp config

composer.json, composer.lock
=> chore: update phpspreadsheet package

config/seckit.settings.yml
=> chore: add csp config for powerbi

composer.lock
=> updates: update select_a11y and phpoffice packages

composer.lock, composer.patches.json
=> updates: update patch and update modules

config/seckit.settings.yml
=> chore: add csp exception for clarity

.github/workflows/composer-update-config.yml, .github/workflows/composer-update.yml
=> chore: Use the visible / editable maintainers var for PR assignment.

.github/workflows/composer-update-config.yml, .github/workflows/composer-update.yml, composer.lock
=> chore: Update main with recent routine updates for monthly deploy.
